before_script:
  - sudo apt-get update
test:
  script:
  - echo 'Starting Tests'
  - sudo yarn test
pull:
  script:
  - echo 'Starting deploy'
  - sudo git -C /root/alltitude pull
  - echo 'Build Nuxt'
  - sudo yarn --cwd /root/alltitude/ build
