variables:
  GIT_STRATEGY: none
before_script:
  - sudo apt-get update
  - sudo git clone git@gitlab.com:pcr2043/alltitude.git
testing:
  stage: build
  script:
  - echo 'Starting Tests'
  - sudo yarn
  - sudo chown -R gitlab-runner:gitlab-runner .
  - sudo yarn test 
deploing:
  stage: test
  script:
  - echo 'Starting deploy'
  - sudo git -C /root/alltitude pull
  - echo 'Build Nuxt'
  - sudo yarn --cwd /root/alltitude/ build
