variables:
  GIT_STRATEGY: none
before_script:
  - sudo apt-get update
installing:
  stage: build
  script:
  - echo 'Manually'
  - sudo rm -rf alltitude
  - sudo git clone git@gitlab.com:pcr2043/alltitude.git
  - sudo yarn 
testing:
  stage: build
  script:
  - echo 'Starting Tests'
  - sudo yarn test 
deploing:
  stage: test
  script:
  - echo 'Starting deploy'
  - sudo git -C /root/alltitude pull
  - echo 'Build Nuxt'
  - sudo yarn --cwd /root/alltitude/ build
