image: node:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - coverage/
before_script:
  - npm install
deploing:
  stage: test
  script:
  - echo 'Starting deploy'
  - git -C /root/alltitude pull
  - sudo npm --cwd /root/alltitude/ build
