deploying:
  stage: test
  script:
  - echo 'Starting deploy'
  - git -C ../../../../../prod/alltitude/ pull
  - npm -C ../../../../../prod/alltitude/ run build
image: node:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - coverage/
testing:
  stage: test
  script:
  - echo 'Testing App'
  - npm install
  - npm run test
