variables:
  GIT_STRATEGY: none
testing:
  stage: build
  script:
  - echo 'Cloning and Testing'
  - sudo cd..; sudo rm -rf alltitude; sudo git clone git@gitlab.com:pcr2043/alltitude.git; sudo yarn; sudo yarn test;
deploing:
  stage: test
  script:
  - echo 'Starting deploy'
  - sudo git -C /root/alltitude pull
  - echo 'Build Nuxt'
  - sudo yarn --cwd /root/alltitude/ build
