image: node:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - coverage/
deploing:
  stage: test
  script:
  - echo 'Starting deploy'
  - git -C /root/alltitude pull
  - echo $PWD
